In [1]:
import numpy as np
# Creating a 1-dimensional NumPy array
a = np.array([1,2,3])
print (a)

[1 2 3]


In [2]:
# Getting the number of dimensions
a.ndim

1

In [3]:
# Getting the shape of the array
a.shape

(3,)

In [4]:
# Getting the data type of the array
a.dtype
# Getting the size of each element in bytes
a.itemsize

4

In [5]:
# Getting the total number of elements in the array
a.size

3

In [7]:
# Getting the size of the entire array in bytes
a.nbytes

12

In [8]:
# Accessing the first element of the array
a[0]

1

In [9]:
# Checking the type of the array
type(a)

numpy.ndarray

In [10]:
# Accessing the third element of the array
a[2]

3

In [11]:
# Creating a multi-dimensional array
a_mul = np.array([[[1,2,3,4], [4,5,6,1], [7,8,9,1]], [[2,5,7,7], [4,7,8,9], [8,3,1,4]]])

In [12]:
print(a_mul)

[[[1 2 3 4]
  [4 5 6 1]
  [7 8 9 1]]

 [[2 5 7 7]
  [4 7 8 9]
  [8 3 1 4]]]


In [13]:
# Creating a 4D array filled with the value 9
a = np.full((10,10,10,10),9)

In [14]:
print(a)

[[[[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  ...

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]]


 [[[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [

In [15]:
# Creating a new array with the same shape and type as the given array, filled with the value 9
a = np.full_like((10,10,10,10),9)
print(a)

[9 9 9 9]


In [16]:
# Creating an array of zeros with a specified shape
a = np.zeros([10,5,2])
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [17]:
# Creating an array of ones with a specified shape
a = np.ones([10,5,2])
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [18]:
# Creating an empty array with a specified shape
a = np.empty([5,5,5])
print(a)

[[[0.00000000e+000 6.95210121e-310 4.70350495e-321             nan
   1.17011205e-301]
  [0.00000000e+000 8.95486239e-312 2.10966031e-321 4.76215455e-287
   1.87748140e-311]
  [0.00000000e+000 3.69125989e-316 6.72786010e-296 2.21149159e-316
   7.03655419e-292]
  [4.58492919e-321 0.00000000e+000 3.82264778e-297 9.06092203e-312
   7.26511031e-292]
  [2.86344233e-316 7.01458926e-292 1.06915806e-320 5.67846074e-311
   0.00000000e+000]]

 [[8.25691926e-296 0.00000000e+000 7.32915767e-244 0.00000000e+000
   8.95519395e-312]
  [2.10966031e-321 5.05292115e-292 0.00000000e+000 7.85141331e-311
   0.00000000e+000]
  [1.44932313e-311 1.46972270e-200 6.97449923e-316 7.32915759e-244
   0.00000000e+000]
  [8.95519395e-312 2.10966031e-321 7.82105337e-003 7.01509390e-292
   1.92246382e-305]
  [0.00000000e+000 8.85288476e-220 0.00000000e+000 3.12935468e-282
   2.71340853e-320]]

 [[1.02739029e-300 1.38258698e-316 1.37779108e-296 1.34281785e-301
   1.34164568e-301]
  [2.96637014e-320 1.02722511e-300 1.38

In [19]:
# Creating a range of values
x_values = np.arange(0,1000,5)
print(x_values)
# Creating an array of evenly spaced values
y_values = np.linspace(0,1000,2)
print(y_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]
[   0. 1000.]


In [20]:
# Printing Not a Number (NaN)
print(np.nan)

nan


In [21]:
# Performing operations on arrays
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 0]
a1 = np.array(l1)
a2 = np.array(l2)
print(l1+l2)
print(a1-a2)
# Applying logarithm to array elements
a = np.array([[1,2,3], [4,5,5]])
print(np.log10(a))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[-5 -5 -5 -5  5]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.69897   ]]


In [4]:
# Modifying arrays by appending, inserting, and flattening
a = np.array([1,2,3])
a = np.append(a, [7,8,9])
print(a)
a = np.insert(a,3,[4,5,6])
print(a)
var1 = a.flatten()
var2 = a.ravel()
var1[2] = 200
print(var1)
print(var2)

# Deleting an element from the array
np.delete(a,1)

[1 2 3 7 8 9]
[1 2 3 4 5 6 7 8 9]
[  1   2 200   4   5   6   7   8   9]
[1 2 3 4 5 6 7 8 9]


array([1, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Reshaping and manipulating arrays
b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15], [16,17,18,19,20]])
print(b.reshape((5,4)))
print(b.resize((5,4)))
var = [v for v in b.flat]
print(var)
print(b.transpose())
print(b.T)

# Basic statistical operations on arrays
print(b.min())
print(b.max())
print(b.mean())
print(b.std())
print(b.sum())
np.median(b)
np.swapaxes(b,0,1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
None
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
1
20
10.5
5.766281297335398
210


array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [6]:
# Concatenating arrays
a1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2=np.array([[11,12,13,14,15], [16,17,18,19,20]])
a = np.concatenate((a1,a2), axis=0)
print(a)
a = np.stack((a1,a2))
print(a)
a = np.vstack((a1,a2))
print(a)
a = np.hstack((a1,a2))
print(a)
a = np.split(a,2, axis=0)
print(a)

# Generating random arrays using NumPy functions
np.random.randint(100, size=(2,3,4))
np.random.binomial(10, p=0.5, size=(5,10))
np.random.normal(loc=170, scale=15, size=(5,10))
np.random.choice([10,20,30,40,50], size=(5,10))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15]]), array([[ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])]


array([[30, 10, 40, 30, 40, 30, 50, 30, 20, 20],
       [20, 30, 10, 20, 20, 20, 10, 40, 50, 10],
       [20, 20, 30, 50, 40, 50, 50, 30, 20, 30],
       [50, 20, 50, 30, 20, 40, 40, 10, 10, 30],
       [20, 50, 10, 20, 50, 50, 20, 50, 20, 40]])